version = 3.8.1

runner.dialect = scala3
rewrite.scala3 = true
rewrite.scala3.preset = true


maxColumn = 120

align.preset = more
align.multiline = true
align.stripMargin = true

indent.defnSite = 2
indent.extendSite = 2
indent.withSiteRelativeToExtends = 2

newlines.alwaysBeforeMultilineDef = false
newlines.beforeMultiline = keep
newlines.afterCurlyLambda = preserve

rewrite.rules = [RedundantBraces, RedundantParens, SortImports]
rewrite.redundantBraces.stringInterpolation = true
rewrite.redundantBraces.includeUnitMethods = true

spaces.afterKeywordBeforeParen = true
spaces.beforeContextBoundColon = true

docstrings.style = Asterisk
docstrings.wrap = no

includeCurlyBraceInSelectChains = false
includeNoParensInSelectChains = true

optIn.breakChainOnFirstMethodDot = false
optIn.configStyleArguments = true
optIn.forceBlankLineBeforeDocstring = false

binPack.literalArgumentLists = true
binPack.parentConstructors = true

continuationIndent.defnSite = 2
continuationIndent.extendSite = 2

danglingParentheses.preset = true
danglingParentheses.exclude = [class, trait, enum]

verticalMultiline.atDefnSite = false
verticalMultiline.newlineAfterOpenParen = false
verticalMultiline.arityThreshold = 100

