#!/bin/sh
java -Dnet.snowflake.jdbc.loggerImpl=net.snowflake.client.log.SLF4JLogger \
  --add-opens=java.base/java.nio=org.apache.arrow.memory.core,ALL-UNNAMED \
  -jar "${DFENCE_JAR_PATH:-target/zoom-data-fence-jar-with-dependencies.jar}" $@
