# frozen_string_literal: true

ruby file: ".ruby-version"
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "jekyll"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "rouge"
