name: build-deploy
on:
  push:
    branches:
      # Build Snapshots From Main
      - main
    tags:
      # Build Releases From Tags
      - v*.*.*
permissions:
  contents: read
jobs:
  get-version:
    environment: deploy
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      deploy: ${{ steps.determine-deploy.outputs.deploy }}
      release: ${{ steps.determine-deploy.outputs.release }}
      java-version: ${{ steps.set-constants.outputs.java-version }}
      java-distribution: ${{ steps.set-constants.outputs.java-distribution }}
    steps:
      - uses: actions/checkout@v4
      - name: Set Constants
        id: set-constants
        run: |
          echo "java-version=17" >> $GITHUB_OUTPUT
          echo "java-distribution=temurin" >> $GITHUB_OUTPUT
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ steps.set-constants.outputs.java-version }}
          distribution: ${{ steps.set-constants.outputs.java-distribution }}
          cache: maven
      - name: Extract Maven project version
        run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
        id: get-version
      - name: Determine if Deploy
        id: determine-deploy
        # We want to build releases from tags matching the correct pattern and matching the pom version.
        # We want to build snapshot releases from any push to main.
        uses: actions/github-script@v6
        env:
          VERSION: ${{ steps.get-version.outputs.version }}
          REF: ${{ github.ref }}
        with:
          script: |
            const versionPattern = /[0-9]+\.[0-9]+\.[0-9]/;
            const snapshotPattern = /[0-9]+\.[0-9]+\.[0-9]-SNAPSHOT/;
            const REF = process.env.REF;
            const VERSION = process.env.VERSION;
            
            if (`refs/tags/v${VERSION}` === REF && versionPattern.test(VERSION)) {
              core.setOutput('deploy', true);
              core.setOutput('release', true);
            } else if (REF === 'refs/heads/main' && snapshotPattern.test(VERSION)) {
              core.setOutput('deploy', true);
              core.setOutput('release', false);
            } else {
              core.setOutput('deploy', false);
              core.setOutput('release', false);
            }
  deploy-docker:
    uses: ./.github/workflows/deploy-docker.yml
    needs:
      - get-version
    secrets: inherit
    with:
      deploy: ${{ fromJSON(needs.get-version.outputs.deploy) }}
      release: ${{ fromJSON(needs.get-version.outputs.release) }}
      version: ${{ needs.get-version.outputs.version }}
  deploy-maven:
    uses: ./.github/workflows/deploy-maven.yml
    needs:
      - get-version
    secrets: inherit
    with:
      deploy: ${{ fromJSON(needs.get-version.outputs.deploy) }}
      release: ${{ fromJSON(needs.get-version.outputs.release) }}
      version: ${{ needs.get-version.outputs.version }}
      java-version: ${{ needs.get-version.outputs.java-version }}
      java-distribution: ${{ needs.get-version.outputs.java-distribution }}

