name: Java CI with Maven

on:
  push:
    # ToDo: Replace with tag
    branches: [ "main", "feature/deploy" ]

jobs:
  build:

    runs-on: maven:3.8.5-openjdk-17

    steps:
      - uses: actions/checkout@v4
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
      - name: Show extracted Maven project version
        run: echo ${{ steps.project.outputs.version }}
